### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by wopian** [wopian/hibari#29]
- [ ] Homepage `/`
- [ ] User `/@:slug`
   - [ ] Profile `/@:slug`
   - [ ] Library `/@:slug/library`
- [ ] Anime `/anime/:slug`
- [ ] Manga `/manga/:slug`
- [ ] Overall user stats `/users`
- [ ] Overall anime stats `/anime`
- [ ] Overall manga stats `/manga`
